[package]
name = "range-utils"
version = "0.1.0"
edition = "2021"
description = "Utils to work with ranges"
license = "MIT"
repository = "https://github.com/M1ngXU/range-utils"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
